{% set version = "6.1.0" %}

package:
    name: esys-escript
    version: {{ version }}
source:
    url: https://github.com/LutzGross/esys-escript.github.io/archive/refs/tags/{{ version }}.tar.gz
    sha256: fe2661e883e8f9e0dc12af675eb83e64abacc6039ab87b534d3630204778006e
build:
    number: 0
requirements:
    build:
        - {{ compiler('cxx') }}
        - {{ compiler('fortran') }}
        - {{ stdlib("c") }}
        - scons
        - cmake
        - make
        - python
        - setuptools
        - numpy
        - git
    host:
        - libboost-devel
        - libboost-python-devel
        - numpy
        - python
        - setuptools
        - matplotlib-base
        - hdf5
        - libopenblas  # [unix]
        - llvm-openmp  # [unix]
        - pyproj
        - scipy
        - sympy
        - suitesparse  # [unix]
        - gmsh  # [win]
    run:
        - python
        - matplotlib-base
        - llvm-openmp  # [unix]
        - hdf5
        - pyproj
        - scipy
        - sympy
        - gmsh  # [win]
        - setuptools  # [py>=312]
test:
    commands:
        - run-escript -c
        - run-escript /tmp/release_sanity.py  # [linux]
        - run-escript %TEMP%/release_sanity.py  # [win]
about:
    home: https://github.com/LutzGross/esys-escript.github.io
    summary: esys-escript is a programming tool for implementing mathematical
        models in python using the finite element method (FEM).
    license: Apache-2.0
    license_file: LICENSE
    description: esys-escript is a programming tool for implementing
        mathematical models in python using the finite element method (FEM).
        As users do not access the data structures it is very easy to use and
        scripts can run on desktop computers as well as highly parallel
        supercomputer without changes. Application areas for escript include
        earth mantle convection, geophysical inversion, earthquakes,
        porous media flow, reactive transport, plate subduction, erosion,
        and tsunamis.
    dev_url: https://github.com/LutzGross/esys-escript.github.io
    doc_url: https://lutzgross.github.io/esys-escript.github.io/

extra:
    recipe-maintainers:
        - esys-escript
